name: CI Workflow Demo
# Copy this one into your own repository- change up the things your secrets reference if necessary, and run!
on:
  workflow_dispatch:
  push:
    branches: [dev] # replace this with whatever branch you want to push from.
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * SUN"


jobs:
  clasp-update-aio:
    runs-on: ubuntu-latest
    steps:
    - name: Call Reusable Action
      uses: texas-mcallen-mission/deploy-google-app-script-action-typescript/@get-off-deprecated-stuff  #@testing-actions-caching
      with:
      # secrets:
        # THESE are the ones that are deployment-specific.
        CLASP_TOKEN_VALUE: ${{ secrets.CLASPRC_JSON }}
        CLASP_TOKEN_NAME: 'CLASPRC_JSON'
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        USES_ORG_SECRET: false # optional.
        # ORG_VISIBILITY: all # optional, default all.
        SCRIPT_ID: ${{ secrets.SCRIPT_ID_DEV }}
        PARENT_ID: ${{ secrets.PARENT_ID_DEV }} # optional.
        DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }} # optional.
        CONFIG_DATA: ${{ secrets.CONFIG_DATA }} # optional.
