name: CI Workflow Demo
# Copy this one into your own repository- change up the things your secrets reference if necessary, and run!
on:
  workflow_dispatch:
  push:
    branches: [dev]
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * SUN"


jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
    - name: Call Reusable Action
      uses: texas-mcallen-mission/deploy-google-app-script-action-typescript/@get-off-deprecated-stuff
      with:
        # Github repository information
        sha: ${{ github.sha }}
        event_name: ${{ github.event_name }}
        actor: ${{ github.actor }}
        job: ${{ github.job }}
        repository: ${{ github.repository }}
        ref_name: ${{ github.ref_name }}
      # secrets:
        # THESE are the ones that are deployment-specific.
        CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        SCRIPT_ID: ${{ secrets.SCRIPT_ID_DEV }}
        DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }} # optional.
        PARENT_ID: ${{ secrets.PARENT_ID_DEV }} # optional.
        CONFIG_DATA: ${{ secrets.CONFIG_DATA }} # optional.
        